### ISSUE TITLE
Authentication in conf file not getting reflected in execution of plugin 

### ISSUE THREAD

**Issue by cminder** [marklogic/newrelic-plugin#11]
In running the MarkLogic newrelic plugin, when setting auth to Basic, it is not getting reflected in the request.  This is the conf file entry.
# Authentication to use when accessing MarkLogic management REST API (BASIC|DIGEST).

auth= BASIC
I put debug code in  http_utils.py 
            log.debug("auth:")
            log.debug(auth)
And this is the output after running in debug mode:
2016-10-27 08:49:00,618 newrelic_marklogic_plugin.http_utils DEBUG    auth:
2016-10-27 08:49:00,618 newrelic_marklogic_plugin.http_utils DEBUG    <requests.auth.HTTPDigestAuth object at 0x7f3f58388590>

**Comment by xquery** [comment]
nice catch, fixed.
