### ISSUE TITLE
proxy not setting was string indices must be integers, not str argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by cminder** [marklogic/newrelic-plugin#6]
I am attempting to upload a payload to newrelic.  I get the error in the subject line.  Below is my payload.

{"components": [{"duration": 60, "metrics": {}, "guid": "com.marklogic", "name": "marklogic"}], "agent": {"host": "10.153.158.66", "version": "0.2.3", "pid": 1}}
Here are some of my variables
headers
{'Content-Type': 'application/json', 'X-License-Key': '0c48c80a186af49408b5958f453dcc78572cbb47', 'Accept': 'application/json'}
url
https://platform-api.newrelic.com/platform/v1/metrics
proxy
http://newrelicproxy.ecap.cciio:3128,https://newrelicproxy.ecap.cciio:3128

Code where it fails:

 try:
            return HTTPUtil.http_post(
                scheme="https",
                url="https://platform-api.newrelic.com/platform/v1/metrics",
                headers={'Accept': 'application/json',
                         'Content-Type': 'application/json',
                         'X-License-Key': key},
                payload=data,
                proxy=proxy)
        except Exception as e:
            log.error("Problem accessing NewRelic Plugin API")
            log.error(e)
            pass

**Comment by xquery** [comment]
This appears to be a connection issue eg. newrelic plugin is not able to access the NewRelic Plugin API. 

I think I see the issue eg. we are not marshalling supplied proxies into python dict format that request module requires.

Thanks for catching this I will fix and make a new release (tomorrow latest).

**Comment by xquery** [comment]
as a workaround you might be able to set proxies via env vars

```
export HTTP_PROXY="http://10.10.1.10:3128"
export HTTPS_PROXY="http://10.10.1.10:1080"
```

and have newrelic config blank. 

then run the plugin.
